#Testing

name: CMake on multiple platforms

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'inflection/**'
      - '.github/workflows/**'
      - '!data/**'
      - '!documents/**'
      - '!fst/**'
  push:
    branches:
      - main
    paths:
      - 'inflection/**'
      - '.github/workflows/**'

env:
  ICU_MAJOR: '77'
  ICU_MINOR: '1'

jobs:
  cache-icu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: ~/icu
          key: ${{ runner.os }}-icu-${ICU_MAJOR}-${ICU_MINOR}
      - name: Download and install icu
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/unicode-org/icu/releases/download/release-${ICU_MAJOR}-${ICU_MINOR}/icu4c-${ICU_MAJOR}_${ICU_MINOR}-Ubuntu22.04-x64.tgz
          export ICU=~/icu/
          mkdir -p $ICU
          cp icu4c-${ICU_MAJOR}_${ICU_MINOR}-Ubuntu22.04-x64.tgz $ICU
          pushd $ICU
          tar xvfz *.tgz
          rm *.tgz
      - uses: actions/cache/save@v4
        with:
          path: ~/icu
          key: ${{ runner.os }}-icu-${ICU_MAJOR}-${ICU_MINOR}

  build:
    needs: cache-icu
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release]
        c_compiler: [clang]
        include:
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4

      - name: Fetch Git tags (for versioning)
        run: git fetch --tags

      - name: Create Git LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .git/lfs-hashes.txt

      - name: Restore Git LFS object cache
        uses: actions/cache@v4
        id: lfscache
        with:
          path: inflection/resources/org/unicode/inflection/dictionary
          key: ${{ runner.os }}-lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
          restore-keys: |
            ${{ runner.os }}-lfsdata-v1-
            ${{ runner.os }}-lfsdata

      - name: Fetch missing Git LFS files
        if: steps.lfscache.outputs.cache-hit != 'true'
        run: git lfs fetch --prune

      - name: Checkout Git LFS content
        if: steps.lfscache.outputs.cache-hit != 'true'
        run: git lfs checkout

      - name: Debug Git LFS content
        run: ls -lh inflection/resources/org/unicode/inflection/dictionary/

      - name: Set reusable paths
        id: strings
        shell: bash
        run: |
          echo "project-root-dir=${{ github.workspace }}/inflection" >> "$GITHUB_OUTPUT"
          echo "build-output-dir=${{ github.workspace }}/inflection/build" >> "$GITHUB_OUTPUT"

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: ~/icu
          key: ${{ runner.os }}-icu-${ICU_MAJOR}-${ICU_MINOR}

      - name: Install ICU (Ubuntu/macOS)
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "ICU_ROOT=~/icu/icu/usr/local" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew list icu4c || brew install icu4c
            ICU_PREFIX=$(brew --prefix icu4c)
            echo "ICU_ROOT=$ICU_PREFIX" >> $GITHUB_ENV
            echo "CMAKE_INCLUDE_PATH=$ICU_PREFIX/include" >> $GITHUB_ENV
            echo "CMAKE_LIBRARY_PATH=$ICU_PREFIX/lib" >> $GITHUB_ENV
          fi

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DICU_ROOT=$ICU_ROOT
          -DCMAKE_PREFIX_PATH=$ICU_ROOT
          -S ${{ steps.strings.outputs.project-root-dir }}

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j ${{ steps.cpu-cores.outputs.count }}

      - name: Run tests
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: cmake --build . -t check -j ${{ steps.cpu-cores.outputs.count }}

      - name: Package with CPack
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: |
          cpack
          ls -lh *.tar.gz *.deb || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-inflection-artifacts
          path: |
            ${{ steps.strings.outputs.build-output-dir }}/*.deb
            ${{ steps.strings.outputs.build-output-dir }}/*.tar.gz
          retention-days: 30

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Release ${{ github.ref_name }}"
          files: |
            ${{ steps.strings.outputs.build-output-dir }}/*.deb
            ${{ steps.strings.outputs.build-output-dir }}/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

